### ISSUE TITLE
"How to build" instructions fail

### ISSUE THREAD

**Issue by grahamannett** [AdguardTeam/AdGuardMiniForMac#315]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I am trying to follow the instructions to run in development mode.  I have everything set up and working until the `yarn install` instruction.  

This gives me an issue related to:

```
error /Users/graham/code/Safari_EXT/AdGuardForSafari/ElectronMainApp/node_modules/safari-ext: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/graham/code/Safari_EXT/AdGuardForSafari/ElectronMainApp/node_modules/safari-ext
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.9.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/graham/.asdf/installs/nodejs/12.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/graham/code/Safari_EXT/AdGuardForSafari/ElectronMainApp/node_modules/safari-ext/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/graham/.asdf/installs/nodejs/12.9.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/graham/Library/Caches/node-gyp/12.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/graham/Library/Caches/node-gyp/12.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/graham/.asdf/installs/nodejs/12.9.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/graham/Library/Caches/node-gyp/12.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/graham/code/Safari_EXT/AdGuardForSafari/ElectronMainApp/node_modules/safari-ext',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/safari_ext_addon/src.o
../src.mm:3:9: fatal error: 'shared/AESharedResources.h' file not found
#import "shared/AESharedResources.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/safari_ext_addon/src.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/graham/.asdf/installs/nodejs/12.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/graham/.asdf/installs/nodejs/12.9.1/bin/node" "/Users/graham/.asdf/installs/nodejs/12.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/graham/code/Safari_EXT/AdGuardForSafari/ElectronMainApp/node_modules/safari-ext
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
```

I dont know what to do exactly since I am following the instructions.  I see that there is a top level shared folder and a  I have tried building the shared libraries from Xcode and it puts it into a folder "/Users/graham/Library/Developer/Xcode/DerivedData/AdGuard-bvtnjfhupcxloufuyswdsylgglkp/Build/Products/Debug/libshared.a"

Am I missing some configuration set up or do I need to do something?  I have tried a few things with the Shared folder but will get an issue that it cant find the libshared then when installing safari-ext.

Thanks

**Comment by Mizzick** [comment]
Hello!
Have you tried just to 
```
/bin/bash ./build.sh beta --notarize=0
```

**Comment by grahamannett** [comment]
yep.  played around with all the shell files to see if they would build or fix any issues or what not but no luck.

**Comment by Mizzick** [comment]
@grahamannett 
might you try with the following versions?
```
node-gyp v3.8.0
node v12.6.0
```

Also it might be helpful to build with xcode for a first time, have tried?
